### ISSUE TITLE
Rust9x refuses to compile because the Rust build it is based off of doesn't have archives in Rust servers anymore

### ISSUE THREAD

**Issue by ghost** [rust9x/rust#31]
![image](https://github.com/rust9x/rust/assets/167991948/c9ea08e5-6b0d-421f-a0e0-5218db968793)

**Comment by ghost** [comment]
(To clarify, I'm not using Windows 7, this is Windows 10 customized to look like it)

**Comment by seritools** [comment]
Interesting - as a workaround I think you can set

```toml
[llvm]
download-ci-llvm = false
```

in the config. Seems like old LLVM builds are deleted from the artifacts repo after some time https://github.com/rust-lang/rust/issues/123956.

**Comment by ghost** [comment]
Nope, it didn't work.
![image](https://github.com/rust9x/rust/assets/167991948/b22ca906-cc19-460e-85d7-5408a048dcde)

**Comment by seritools** [comment]
Did you install cmake as required by the LLVM compile step (just like it says on the screenshot ^^).

Just as a note: I didn't have luck compiling that LLVM version with MSVC++ 2022 17.11.0 Preview 2.1, it likely needs VS2019 to compile properly.

All of this will be resolved once I to rebase and port rust9x to a newer Rust version of course, but no ETA for that.

**Comment by the-r3dacted** [comment]
I do have a VM that works to build LLVM and Rust, but I have no idea how to replicate this. I'll have to give it a try later to see what all I need.

Here is my config btw (works for 1.76.0 too)
https://github.com/Eclipse-Community/eRust/blob/mod-1.77.2/config.toml

Edit: See if you can get it to compile with this, since I made this from officially installed MSVC2019 in my 10 VM I'm now using for Rust.

https://archive.org/details/funny-windows-development-kit
